# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:2026.02.0
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '80:80/tcp'
      - '443:443/tcp'
    environment:
      TZ: 'Asia/Kolkata'
      FTLCONF_webserver_api_password: ${WEBPASSWORD}
      FTLCONF_dns_upstreams: '172.20.0.3#5300' ## dnscrypt's IP
      FTLCONF_dns_listeningMode: 'SINGLE'
      FTLCONF_dns_interface: 'eth0'
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - './etc-pihole:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    networks:
      pihole:
        ipv4_address: 172.20.0.2
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      # - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped

  dnscrypt:
    container_name: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy:2.1.15
    networks:
      pihole:
        ipv4_address: 172.20.0.3
    expose:
      - '5300/udp'
      - '5300/tcp'
    environment:
      TZ: 'Asia/Kolkata'
    volumes:
      - './dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml'
    dns:
      - 1.1.1.1
    restart: unless-stopped

networks:
  pihole:
    name: pihole_network
    ipam:
      config:
        - subnet: 172.20.0.0/24
