version: '3.5'

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:2024.07.0
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '80:80/tcp'
      - '443:443/tcp'
    environment:
      TZ: 'Asia/Kolkata'
      VIRTUAL_HOST: 'pi.hole'
      PROXY_LOCATION: 'pi.hole'
      WEBPASSWORD: ${WEBPASSWORD}
      # ServerIP: ${HOST_IP}
      DNS1: '172.20.0.3#5300' ## dnscrypt's IP
      DNS2: 'no' ## we don't want to use secondary dns server to make sure all our dns queries are going through cloudflared

      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    networks:
      pihole:
        ipv4_address: 172.20.0.2
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped

  dnscrypt:
    container_name: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy:2.1.5
    networks:
      pihole:
        ipv4_address: 172.20.0.3
    expose:
      - '5300/udp'
      - '5300/tcp'
    environment:
      TZ: 'Asia/Kolkata'
    volumes:
      - './dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml'
    dns:
      - 1.1.1.1
    restart: unless-stopped

networks:
  pihole:
    name: pihole_network
    ipam:
      config:
        - subnet: 172.20.0.0/24
